site_name: Past Dream
site_description: Past Dream's blog
site_url: https://pastdream.github.io/
nav:
    - Home: index.md
    - ICS: 
        - ICS: ics/ics_pre.md
        - ICS_PA(x86): 
          - 在PA开始之前（x86）: ics/ics_pa_pre.md
          - PA 4-1 来自外部的声音: ics/pa/ics_pa-4-1.md
          - PA 4-2 冯诺依曼的构想: ics/pa/ics_pa-4-2.md
          - PA 4-3 编写不朽的传奇: ics/pa/ics_pa-4-3.md
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  features:
    - navigation.tabs # 启用顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16